### ISSUE TITLE
No build/distributions directory after ./gradlew build

### ISSUE THREAD

**Issue by bkiefer** [marytts/voice-istc-lucia-hsmm#1]

**Comment by insa-k** [comment]
Hello Bernd,

could you be more specific? 
If you look for something like a .jar file, it is located under `build/libs`.
In general the `build/distributions` directory is only created when the [Distribution Plugin](https://docs.gradle.org/current/userguide/distribution_plugin.html) is applied in the `build.gradle` which it is not at the moment. You can of course fork this repo and adapt it to your needs.
Hope this helps!

Best regards
Insa
